### ISSUE TITLE
Overriding submodule sass includes

### ISSUE THREAD

**Issue by BenDarby** [cis-bathnes/pattern-lib#1]
We need to find a way of either excluding the _colours.scss import from the govuk_frontend_toolkit submodule when it's being imported from another .scss we need from the toolkit. Or we need to find a way to override the GOV UK colours with the BATHNES brand colours even when the GOV UK ones are imported via the submodule. 

At the moment the style guide is not picking up our colour variables which are built on top of the GOV UK variables.

**Comment by benjamincoleman** [comment]
@urlsangel can you comment and close this one? I know you've solved it.

**Comment by urlsangel** [comment]
Added duplication task to gulpfile to copy SASS files in compile step, stripping out `@import` statements at the same time.
