### ISSUE TITLE
"Change" link has no context

### ISSUE THREAD

**Issue by ghost** [cis-bathnes/pattern-lib#12]
![image](https://user-images.githubusercontent.com/609519/34771766-a4d32de6-f5fd-11e7-9711-d70828cd9718.png)
Change link currently has no context, use of aria-label could provide more meaning.
Note: Issue #11 will fix this however the above fix will ensure context is given.

Reference: Templates > Check Your Answers

**Comment by BenDarby** [comment]
Used an aria-label to help provide context for the change link
