### ISSUE TITLE
Reference the images folder from the frontend-toolkit submodule

### ISSUE THREAD

**Issue by BenDarby** [cis-bathnes/pattern-lib#2]
We need to find a way reference the path to use govuk_frontend_toolkit submodule images folder in our .scss file so are able to pull on their icons. This way, if the GOV UK fontend toolkit gets updated with new icons then they will get pulled in for use with the BATHNES style guide

**Comment by benjamincoleman** [comment]
@urlsangel can you comment and close this one? I know you've solved it.

**Comment by urlsangel** [comment]
Added `'govuk_frontend_toolkit/images/**/*'` to gulpfile image src on compile.
