### ISSUE TITLE
Import javascript from GOV UK frontend toolkit

### ISSUE THREAD

**Issue by BenDarby** [cis-bathnes/pattern-lib#3]
As we're using elements from the GOVUK frontend toolkit we need to find a way of importing their javascript from the submodule so the interaction with elements such as forms will work. Ideally we want to reference/import from the submodule so if they update it in the future it will update on the BATHNES site as well.

**Comment by benjamincoleman** [comment]
Sorted this - need to import the right modules from them to cover dependencies.
