### ISSUE TITLE
Non-specific Link Text

### ISSUE THREAD

**Issue by ghost** [cis-bathnes/pattern-lib#4]
![image](https://user-images.githubusercontent.com/609519/34079772-3309aff2-e32c-11e7-9064-57feac2dc617.png)

Ensure link text such as "more" is never used without either of the following criteria:

- A heading above provides context to the link (such as "Latest News" with a "View More" link below)
- More context is provided to screen reader users via hidden text or the aria-label attributes (such as `aria-label="View More Latest News"`) 

Note: aria-label overwrites the contained text so this must be repeated.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/609519/34079833-70f69eaa-e32d-11e7-9d31-c7f2eeef07f3.png)
Similarly "Feedback" requires more context

**Comment by BenDarby** [comment]
Changed the more text to view more and added aria-label to to the <a>

**Comment by ghost** [comment]
Also Occurs in template.

Reference: Templates > Example Typography

**Comment by BenDarby** [comment]
addd aria-label to to link
