### ISSUE TITLE
Unescaped HTML

### ISSUE THREAD

**Issue by ghost** [cis-bathnes/pattern-lib#5]
![image](https://user-images.githubusercontent.com/609519/34079972-566fa214-e32f-11e7-9e46-06219ebdb31a.png)
![image](https://user-images.githubusercontent.com/609519/34079975-68479c44-e32f-11e7-8765-8ae3274354ba.png)

Unescaped example HTML used

**Comment by BenDarby** [comment]
Fixed by adding <code> markup to any notes that require it.
