### ISSUE TITLE
Fieldset with multiple inputs and missing labels

### ISSUE THREAD

**Issue by ghost** [cis-bathnes/pattern-lib#7]
![image](https://user-images.githubusercontent.com/609519/34080203-29f611ca-e332-11e7-9c41-804436c42ed7.png)

Where multiple inputs are used together they should be included in a fieldset and input elements must always have an associated label. In this instance the current label should become a fieldset legend with separate labels used for each input (Note these can be visually hidden). For example:

```
<div class="form-group-related">
   <fieldset>
      <legend>Building and Street</legend>
      <label for="building-street-f1" class="visually-hidden">Address Line 1</label>
      <input class="form-control" id="building-street-f1" type="text" name="building-street-f1">
      <label for="building-street-f2" class="visually-hidden">Address Line 2</label>
      <input class="form-control" id="building-street-f2" type="text" name="building-street-f2">
   </fieldset>
</div>
```

Note: Fieldsets can be nested

**Comment by BenDarby** [comment]
Used the solution above across any fields where this occurs.
