### ISSUE TITLE
Repeated IDs

### ISSUE THREAD

**Issue by ghost** [cis-bathnes/pattern-lib#8]
![image](https://user-images.githubusercontent.com/609519/34080308-b9140000-e333-11e7-8fb3-14bb0d92f7a9.png)
Pattern library contains multiple elements with the same ID, it would be better if these were unique.

**Comment by BenDarby** [comment]
These have duplicate IDs because they are variations of the same component to help illustrate the different scenarios for using some form elements. I've made a note in the forms section of the toolkit to use unique IDs for form fields when building out a form.

**Comment by benjamincoleman** [comment]
this is fine - in implementation there should not be duplicates
